### PR TITLE
CMakeLists.txt: update libQtOlm to 3.0.0

### PR DESCRIPTION
**Pull request by PureTryOut**
libQtOlm now follows the Olm versioning, and is thus 3.0.0 atm.

### CODE REVIEW

**Comment by PureTryOut** [comment]
Travis failing seems unrelated, seems to fail to connect to the homeserver.

**Comment by KitsuneRal** [comment]
Yep, it's missing the test account password that your PR is not allowed to get a hold of :)

Thanks but as mentioned in the room I'd like to see something like 3.0.1 from @encombhat that would incorporate [!6](https://gitlab.com/b0/libqtolm/-/merge_requests/6)

**Comment by PureTryOut** [comment]
@kitsune, 3.0.1 has been tagged. Do I need to update the version check here or will CMake just check for the major version?

**Comment by KitsuneRal** [comment]
Yes, 3.0.1 in CMakeLists.txt please.

**Comment by PureTryOut** [comment]
Done. To make it a bit easier to package and push upgrades in distributions, could the version dependency be relaxed a little? E.g. required ing 3.x rather than 3.x.x? Or 3.x even maybe?

**Comment by KitsuneRal** [comment]
I think we should be good if we use `COMPATIBILITY SameMajorVersion` in the CMake's `write_basic_package_version_file()` further on.

**Comment by PureTryOut** [comment]
That would be on libQtOlm's side then no?

**Comment by KitsuneRal** [comment]
Yes, compatibility guarantees should come from QtOlm.

**Pull request merged**
