### PR TITLE
Add functionality so that sendEvent can handle events with file content.

### PR DESCRIPTION
**Pull request by nvrWhere**
Title

### CODE REVIEW

**Comment by TobiasFella** [comment]
Do I understand correctly that the intention here is for the client to create an event with the file's url pointing at a local file and the library then uploads that file and sends the event automatically?

**Comment by KitsuneRal** [comment]
I have the same question as Tobias; also, it looks like Quotest is crashing now, something is certainly off.

**Comment by nvrWhere** [comment]
Yeah technically this is what `postFile` does behind the scenes. I'm looking at having NeoChat form most the events itself going forward as it makes it easier to handle all the complexities. However thinking about it this is not a good idea if I want to work this way I should do the upload myself and then create the event to post

**Comment by KitsuneRal** [comment]
There's also an option to send an event with a pre-reserved media id and then upload a file to that id, if that's the UX style you prefer.

**Comment by nvrWhere** [comment]
Indeed, also looking at `postFile` are we happy that in the same vein it effectively creates an event with the local filepath and then replaces when the upload finishes?

**Comment by KitsuneRal** [comment]
Well, that was exactly the intention :) so that the user could see the file they attached even before it's uploaded. I wouldn't mind seeing the whole process driven by the library, but we still want to visualise the uploading process and that requires callouts/callbacks separate from the event sending stuff. So I don't know how much you're getting from pre-packing the event.

**Pull request closed without merging**
