### PR TITLE
Bump API version

### PR DESCRIPTION
**Pull request by KitsuneRal**
I thought of trying to run things a bit different this time around, with soname getting a new number while the library version still starts with 0.8. Hope this makes sense and doesn't cause lots of confusion?

### CODE REVIEW

**Comment by TobiasFella** [comment]
We previously used the minor version for compatibility ifdefs; but we might as well check patch version >= 50 so it should be fine

**Review by TobiasFella — DISMISSED** [review]

**Comment by KitsuneRal** [comment]
Hrrm, yeah, good point. Could as well expose `QUOTIENT_API_VERSION` macro to C++ but that also would not be aligned with Qt version checks... I'll think of it a bit more.

**Comment by KitsuneRal** [comment]
Alright, I'm trying to solve an inexistent problem here; there's not much need to distinguish unstable prereleases in purely numeric terms. I'll revert to the previous mechanism.

**Comment by KitsuneRal** [comment]
This way should be better.

**Review by TobiasFella — DISMISSED** [review]

**Pull request merged**
