### PR TITLE
AccountSettings: escape forward- and backslashes in MXIDs

### LINKED ISSUE #842: Accounts with user ids containing forward slashes can't be loaded correctly
Reported as https://bugs.kde.org/show_bug.cgi?id=491252

The user id is used as a key for QSettings, which uses forward slashes as separators. When listing the account, wrong groups are thus returned.

We need to somehow come up with a way of escaping forward slashes while not breaking existing logged-in accounts (at least those that do not contain forward slashes; for the other ones, logging in again is probably inevitable but also not problematic. I haven't been able to come up with a nice way to do that yet.

### PR DESCRIPTION
**Pull request by KitsuneRal**
Fixes #842.

### CODE REVIEW

**Comment by KitsuneRal** [comment]
The test is screwed (and should really be a unit test, not a part of quotest) but the functionality seems to be working, as just tried in Quaternion.

**Comment by TobiasFella** [comment]
This makes the account load fine, but it's not yet perfect: my test account with mxid `@tobias/:matrix.org` is shown as `@tobias%2F:matrix.org`.

<del>(some other things are also broken, but I'd look at those in different issues / patches)</del> actually those might just be symptoms of that problem, let's see

**Comment by KitsuneRal** [comment]
We could add unescaping in some other places; I'm just trying to stay conservative. Technically, it's possible to recover MXIDs even at the `Settings` level, by parsing the key and only (un)escaping only the piece that looks like an MXID - e.g., by using the fact that nobody's using `:` in key names so far, outside of the account names.

**Comment by KitsuneRal** [comment]
Looks like the Windows runner doesn't allow me to store settings in the registry?..

**Comment by KitsuneRal** [comment]
> This makes the account load fine, but it's not yet perfect: my test account with mxid `@tobias/:matrix.org` is shown as `@tobias%2F:matrix.org`.
> 
> ~(some other things are also broken, but I'd look at those in different issues / patches)~ actually those might just be symptoms of that problem, let's see

Okay, I found why this happens, `AccountSettings::userId()` has to unescape the returned value too. Fix coming.

**Comment by KitsuneRal** [comment]
No idea what is happening on Windows CI: it successfully create a settings group for the account but fails to save anything inside the group. Given that it's failing even with "normal" MXIDs, I tend to blame the GitHub runner. Feel free to test it out, if it's fine, I'm merging it.

**Review by TobiasFella — DISMISSED** [review]

**Comment by KitsuneRal** [comment]
I figured the problem on Windows in the end - `QSettings` really wants the organisation name to be explicitly set there, the default empty organisation name doesn't turn into `Unknown organization` as it does on Linux and an empty name for the the registry key doesn't work, of course.

**Pull request merged**
