### PR TITLE
Matrix 1.10

### LINKED ISSUE #731: Update to Matrix 1.10
Updating to the next version of the spec should become (most often) an incremental non-event as it used to be before an upgrade to OpenAPI 3.

### PR DESCRIPTION
**Pull request by KitsuneRal**
The Quotient soft fork of Matrix spec has been too hastily upgraded to Matrix 1.10 that introduced local `$ref` objects in API descriptions, which were not supported by GTAD. It turned out to be relatively straightforward to add this support on GTAD side, so here it goes. Not many significant changes, actually:
- Using a snapshot of to-be-released GTAD 0.11
- Identity services stuff is inlined, one less generated folder (I don't think anybody used it ever?)
- A bit of cleanup in Mustache partials
- Matrix 1.10 renamed `ChildRoomsChunk` to `SpaceHieararchyRoomsChunk` - if you used it (the name; the structure remains the same) in your code, sorry, the thing will break, generated CS API files are not covered by API/ABI portability guarantees

Closes #731.

### CODE REVIEW

**Comment by TobiasFella** [comment]
> generated CS API files are not covered by API/ABI portability guarantees

Do we have that written down somewhere? I'd like to point distros at it, when necessary

**Comment by TobiasFella** [comment]
I'm afraid we are using ChildRoomsChunk by name...

Could we delay that specific change until 0.9?

**Comment by KitsuneRal** [comment]
> > generated CS API files are not covered by API/ABI portability guarantees
> 
> Do we have that written down somewhere? I'd like to point distros at it, when necessary

Errr, looks like we don't. I was under impression that I've put some lines in README.md or at least CONTRIBUTING.md but I don't seem to find that. Anyway, if you use it, I think I can do the reverse-rename just by altering GTAD configuration; will follow up in this PR.

**Comment by KitsuneRal** [comment]
`ChildRoomsChunk` is back; the `*ValidationData` piece still alters the API, formally; but I believe it's not in use so far. But the fact that API/ABI guarantees are implied for these files rather complicates matters. I think I can still roll out a backwards-compatible version of this but it's a bummer.

**Comment by KitsuneRal** [comment]
Heh, apparently I cannot; some changes involve adding arguments (even though with default values) to functions, and that constitutes ABI breakage. Guess I'll have to pin an older version of Matrix spec for libQuotient 0.8.x instead; or just entirely disable automatic API generation in the current stable version.

**Comment by KitsuneRal** [comment]
Given that we're not pushing it for 0.8 any more, `SpaceHierarchyRoomsChunk` is back here again.

**Pull request merged**
