### PR TITLE
switch most deprecation comments to attributes

### PR DESCRIPTION
**Pull request by DeltaNedas**
enables compiler warnings which will help old code get updated.
not sure how to go about the very long explanation, i think the tldr is okay.

### CODE REVIEW

**Comment by ognarb** [comment]
+1 the change looks good to me

**Comment by KitsuneRal** [comment]
Well, you can take a look at the CI breakage in order to understand why I had to resort to comments. In short - Qt's moc historically didn't know about C++ attributes, and I'm not sure it learnt them even as of 5.15. Correct me if I'm wrong.

**Comment by DeltaNedas** [comment]
CI is gettings lots of moc errors as is which seem to be unrelated

**Comment by DeltaNedas** [comment]
ok i fixed em and a "deprecate(" typo, compiles now

should probably fix use of deprecated things within the library too but whatever

**Comment by DeltaNedas** [comment]
good, now it's showing the qt 5.13 bug of not supporting attributes
this can be merged if minimum version is bumped to 5.15 (I'm using 5.15.2-3 from debian sid)

**Comment by KitsuneRal** [comment]
We’re sitting at 5.12 this year. 5.15 should first arrive to stable release of major distributions (RHEL/CentOS, Ubuntu, Suse, namely)

**Comment by KitsuneRal** [comment]
In the end quite a few of those symbols have been deprecated long enough to be simply dropped; and other parts are getting deprecated with `Q_DECL_DEPRECATED_X` that is tolerated by moc even in older Qt versions. See also: https://github.com/quotient-im/libQuotient/compare/kitsune/deprecations

**Pull request closed without merging**
